# Site settings
title: rmqlife Garden 
email: rmqlife@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  "Something interesting or useful will be recorded.
  
  记录一些有趣的或有用的。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rmqlife.github.io" # the base hostname & protocol for your site
twitter_username: rmqlife
github_username:  rmqlife

# Build settings
markdown: kramdown
